#!/usr/bin/env python3
"""
Generate FlexGrip global_mem.mif for 32-bit matrix operands.

IMPORTANT:
    The FlexGrip global_mem.mif is byte-oriented, not word-oriented.
    Therefore each 32-bit encoded element is written as four byte lines
    in little-endian order.

Input file must contain these sections:
    #FULL_A_16x16 encoded
    #FULL_B_16x16 encoded
    #FULL_C_16x16 encoded

Output layout:
    A: row-major, 4 bytes per element, little-endian
    B: column-major, 4 bytes per element, little-endian
       This stores B^T in memory for the Tensor Core feeding convention.
    C: row-major, 4 bytes per element, little-endian

For a 16x16 matrix:
    A occupies 16*16*4 = 1024 bytes = 0x400
    B occupies 16*16*4 = 1024 bytes = 0x400
    C occupies 16*16*4 = 1024 bytes = 0x400
    D starts at 0xC00
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import List


HEX32_RE = re.compile(r"^[0-9A-Fa-f]{1,8}$")


def normalize_hex32(token: str) -> str:
    token = token.strip()

    if not HEX32_RE.fullmatch(token):
        raise ValueError(f"Invalid 32-bit hex token: {token!r}")

    return token.upper().zfill(8)


def word32_to_little_endian_bytes(word_hex: str) -> list[str]:
    """
    Convert AABBCCDD into byte lines DD, CC, BB, AA.

    This matches the byte-oriented global_mem.mif style already used for
    FP16, where each 16-bit value is stored as low byte then high byte.
    """
    word = normalize_hex32(word_hex)
    return [word[6:8], word[4:6], word[2:4], word[0:2]]


def find_section_line(lines: list[str], section_label: str) -> int:
    wanted = section_label.strip().lower()

    for idx, line in enumerate(lines):
        if line.strip().lower() == wanted:
            return idx

    raise ValueError(f"Could not find section label: {section_label}")


def read_matrix_after_section(
    path: Path,
    section_label: str,
    rows: int,
    cols: int,
) -> List[List[str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    start_idx = find_section_line(lines, section_label) + 1

    needed = rows * cols
    tokens: list[str] = []

    for raw in lines[start_idx:]:
        stripped = raw.strip()

        if not stripped:
            continue

        if stripped.startswith("#"):
            if tokens:
                break
            continue

        for token in stripped.split():
            tokens.append(normalize_hex32(token))

        if len(tokens) >= needed:
            break

    if len(tokens) != needed:
        raise ValueError(
            f"Section {section_label!r} contains {len(tokens)} elements; "
            f"expected {needed} for {rows}x{cols}."
        )

    return [tokens[r * cols : (r + 1) * cols] for r in range(rows)]


def flatten_row_major(matrix: List[List[str]]) -> list[str]:
    out: list[str] = []
    for row in matrix:
        out.extend(row)
    return out


def flatten_column_major(matrix: List[List[str]]) -> list[str]:
    rows = len(matrix)
    cols = len(matrix[0]) if rows else 0

    out: list[str] = []
    for c in range(cols):
        for r in range(rows):
            out.append(matrix[r][c])
    return out


def words_to_byte_lines(words: list[str]) -> list[str]:
    out: list[str] = []

    for word in words:
        out.extend(word32_to_little_endian_bytes(word))

    return out


def write_global_mem(path: Path, byte_lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(byte_lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate byte-oriented 32-bit FlexGrip global_mem.mif from encoded A/B/C matrices."
    )
    parser.add_argument("--input", required=True, type=Path, help="Input experiment text file.")
    parser.add_argument("--output", required=True, type=Path, help="Output global_mem.mif path.")
    parser.add_argument("--rows", type=int, default=16, help="Matrix rows. Default: 16.")
    parser.add_argument("--cols", type=int, default=16, help="Matrix columns. Default: 16.")

    args = parser.parse_args()

    A = read_matrix_after_section(args.input, "#FULL_A_16x16 encoded", args.rows, args.cols)
    B = read_matrix_after_section(args.input, "#FULL_B_16x16 encoded", args.rows, args.cols)
    C = read_matrix_after_section(args.input, "#FULL_C_16x16 encoded", args.rows, args.cols)

    words_out = []
    words_out.extend(flatten_row_major(A))
    words_out.extend(flatten_column_major(B))
    words_out.extend(flatten_row_major(C))

    byte_lines = words_to_byte_lines(words_out)

    write_global_mem(args.output, byte_lines)

    print("Generated byte-oriented 32-bit FlexGrip global_mem.mif")
    print(f"Input experiment: {args.input}")
    print(f"Output file:      {args.output}")
    print(f"Matrix shape:     {args.rows}x{args.cols}")
    print(f"A words:          {args.rows * args.cols}")
    print(f"B words:          {args.rows * args.cols}")
    print(f"C words:          {args.rows * args.cols}")
    print(f"Total words:      {len(words_out)}")
    print(f"Total byte lines: {len(byte_lines)}")
    print("Expected D start: 0xC00 for a 16x16 32-bit A/B/C byte layout")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
