
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use ieee.numeric_std.all;
use ieee.std_logic_textio.all;
use std.textio.all;
use work.dpuArray_package.all;

--more sophisticated tests. this testbench takes an input file which
--contains 10 tests of hmma0 instructions each with
--their own different A00, A20, B00, B01, C00, C20 4by4 submatrices.
--(the input file also contains the precomputed values of the 
--D00 and D20 4by4 final submatrices.)
--this testbench focuses on the generation of the W0_16_X3 and W1_16_X3 output signals
--which contain the final submatrices. 
--This testebench also generates an output file which collects the obtained D00 and D20 matrices,
--this file goes input to a script which confronts the D00 and D20 resulting obtained matrices from the hardware described dpu wrt 
--the d00 and d20 matrices which were generated by software and saved in file input to this testbench.


entity octectCoreTopv2Extensive_tb is
--  Port ( );
end octectCoreTopv2Extensive_tb;

architecture sim of octectCoreTopv2Extensive_tb is

--DUT Generics
    
    constant LANES  : integer := 8;
    constant REG_W  : integer := 32;
    constant ELEM_W : integer := 32;

--Clock/config
    constant CLK_PERIOD : time := 10 ns;
    constant WIDTH_FP16 : std_logic_vector(1 downto 0) := "01";
    constant TYPE_FP    : std_logic_vector(2 downto 0) := "000";
    
--DUT signals
    signal clk : std_logic := '0';
    signal rst : std_logic := '1';
    
    signal widthSel : std_logic_vector(1 downto 0) := (others => '0') ;
    signal typeSel  : std_logic_vector(2 downto 0) := (others => '0') ;
    signal load_en  : std_logic := '0' ;
    signal load_ph  : std_logic_vector(1 downto 0) := (others => '0') ;
    signal load_pair: std_logic_vector(1 downto 0) := (others => '0') ;
    signal hmma_step: std_logic := '0' ;
    signal exec_step: std_logic_vector(1 downto 0) := (others => '0') ;
    
    signal rf_rd_data_port_a : arraySize8_32 ;
    signal rf_rd_data_port_b : arraySize8_32 ;
    
    signal W0_8_X3  : arraySize4_8 ;
    signal W1_8_X3  : arraySize4_8 ;
    signal W0_16_X3 : arraySize4_16 ;
    signal W1_16_X3 : arraySize4_16 ;
    signal W0_32_X3 : arraySize4_32 ;
    signal W1_32_X3 : arraySize4_32 ;

    signal step_done : std_logic ;
    
    --type used only for the testbench, in order to be able to reconstruct the matrices from the W0_16_X3 and W1_16_X3 signals respecitivaly
    type matrix4x4_fp16_t is array (0 to 3, 0 to 3) of std_logic_vector(15 downto 0);
    
    --input stimulus file
    --put hmma_step0_tb_input.txt in the simulator working dir
    
    file tb_file : text open read_mode is 
        "C:/Users/giovi/OneDrive/Desktop/Magistrale/Tesi/octectCoreRel0/scritptsRelatedToOctectCoreTopTests/fp16related/hmma_step0_tb_input.txt";
    
    
    file tb_out_file : text open write_mode is 
        "C:/Users/giovi/OneDrive/Desktop/Magistrale/Tesi/octectCoreRel0/scritptsRelatedToOctectCoreTopTests/fp16related/hmma_step0_tb_output.txt";
    
    --helper procedures
    
--1
    procedure clear_rf_ports( --capito
        signal port_a : out arraySize8_32;
        signal port_b : out arraySize8_32
    ) is
    begin 
        port_a <= (others => (others => '0') ) ;
        port_b <= (others => (others => '0') ) ;
    end procedure;

--2
    procedure read_next_port_pair( --procedure used inside of read8lanesfromfile procedure
        file f : text;
        variable val_a : out std_logic_vector(31 downto 0);
        variable val_b : out std_logic_vector(31 downto 0);
        variable ok    : out boolean
    ) is
        variable L : line;
        variable tmp_a : std_logic_vector(31 downto 0);
        variable tmp_b : std_logic_vector(31 downto 0);
    begin
        ok := false;
        
        while not endfile(f) loop
            readline(f, L);
            
            --skip blank lines
            if L = null then
                null;
            elsif L.all'length = 0 then
                null;
            --skip comments
            elsif L.all(1) = '#' then
                null;
            else
                hread(L, tmp_a);
                hread(L, tmp_b);
                val_a := tmp_a;
                val_b := tmp_b;
                ok := true;
                return;
            end if;
        end loop;
    end procedure;

--3
    procedure load_8_lanes_from_file(  --procedure used inside the stimulus process
        file f : text;
        signal port_a : out arraySize8_32 ;
        signal port_b : out arraySize8_32 ;
        variable success : out boolean
    ) is 
        variable v_a : std_logic_vector(31 downto 0);
        variable v_b : std_logic_vector(31 downto 0);
        variable ok : boolean ;
    begin
        success := false;
        
        for i in 0 to 7 loop
            read_next_port_pair(f, v_a, v_b, ok);
            
            if not ok then
                if i = 0 then
                    --no more tests in file
                    return;
                else
                    assert false
                        report "Unexpected EOF while reading a matrix block from stimulus file"
                        severity failure;
                end if;
            end if;
                
            port_a(i) <= v_a ;
            port_b(i) <= v_b ;
        end loop ;
        
        success := true ;
    end procedure;

--4
    procedure write_matrix4x4_hex(
        file f :text;
        constant M: in matrix4x4_fp16_t --this assumes arraySize4_16 contains
                                     --16 half precision values laid out rowMajor
                                     --row0 is indices 0..3, row1 is indices 4 to 7
                                     --row2 is indices 8..11, row3 is indices 12..15
    ) is        
        variable L: line;
    begin
        for r in 0 to 3 loop
            L := null;
            for c in 0 to 3 loop
                hwrite(L, M(r, c));
                if c < 3 then 
                    write(L, string'(" "));
                end if;
            end loop;
            writeline(f, L);
        end loop;
    end procedure;
    
--5 procedure to dump one test_result

procedure write_test_result(
    file f: text;
    constant idx: in integer;
    constant D00: in matrix4x4_fp16_t;
    constant D20: in matrix4x4_fp16_t
    ) is
        variable L : line;
    begin
        L := null;
        write(L, string'("#Test "));
        write(L, idx);
        write(L, string'(" HMMAstep0 related D00 and D20 result submatrices (FP16)"));
        writeline(f,L);
        
        L := null;
        write(L, string'("#D00"));
        writeline(f,L);
        write_matrix4x4_hex(f, D00);
        
        L := null;
        write(L, string'("#D20"));
        writeline(f, L);
        write_matrix4x4_hex(f, D20);
        
        L := null;
        writeline(f, L); --blank line between tests
    end procedure;
begin

    --clock
    
    clk <= not clk after CLK_PERIOD/2 ;
    
    --DUT
    
    dut : entity work. octectCoreTop
        generic map(
            LANES => LANES,
            REG_W => REG_W,
            ELEM_W => ELEM_W
        )
        port map(
            clk => clk,
            rst => rst, 
            widthSel => widthSel,
            typeSel => typeSel,
            load_en => load_en,
            load_ph => load_ph,
            load_pair => load_pair,
            hmma_step => hmma_step,
            exec_step => exec_step,
            rf_rd_data_port_a => rf_rd_data_port_a,
            rf_rd_data_port_b => rf_rd_data_port_b,
            W0_8_X3 => W0_8_X3,
            W1_8_X3 => W1_8_X3,
            W0_16_X3 => W0_16_X3,
            W1_16_X3 => W1_16_X3,
            W0_32_X3 => W0_32_X3,
            W1_32_X3 => W1_32_X3,
            step_done => step_done
        );
     
     --stimulus
     
     stim_proc : process
        variable have_data : boolean;
        variable test_idx : integer := 0;
        variable D00_capture : matrix4x4_fp16_t;
        variable D20_capture : matrix4x4_fp16_t;
        
     begin
        --initial configuration
        widthSel <= WIDTH_FP16;
        typeSel  <= TYPE_FP;
        load_en  <= '0';
        load_ph  <= "00"; -- loading A related Buffer
        load_pair <= "00"; -- slots 0 and 1 are enough for each lanebugger
        hmma_step <= '0'; -- current step of the hmma instruction
        exec_step <= "00"; -- which execution substep out of 4 in order to complete the related 4 by 4 submatrix result
        
        clear_rf_ports(rf_rd_data_port_a, rf_rd_data_port_b);
        
        --reset
        wait for 3*CLK_PERIOD;
        rst <= '0';
        wait for CLK_PERIOD;
        
        --loop over all tests contained in the file
        --each test contributes:
        -- 8 lines for A (A00 and A20 4by4 submatrices
        -- 8 lines for B (B00 and B01 4by4 submatrices
        -- 8 lines for C (C00 and C20 4by4 submatrices
        --comments are skipped automatically
        
        while true loop
            test_idx := test_idx + 1;
            
            --load A
            clear_rf_ports(rf_rd_data_port_a, rf_rd_data_port_b);
            
            load_en <= '1';
            load_ph <= "00"; -- A buffers
            load_pair <= "00";
            
            load_8_lanes_from_file(tb_file, rf_rd_data_port_a, rf_rd_data_port_b, have_data);
            
            exit when not have_data;
            
            wait for CLK_PERIOD;
            load_en <= '0';
            wait for CLK_PERIOD;
            
            --load B
            
            clear_rf_ports(rf_rd_data_port_a, rf_rd_data_port_b);
            
            load_en <= '1';
            load_ph <= "01"; -- B buffers
            load_pair <= "00";
            
            load_8_lanes_from_file(tb_file, rf_rd_data_port_a, rf_rd_data_port_b, have_data);
            
            assert have_data
                report "Stimulus file ended unexpectedly while reading B block for test " &
                    integer'image(test_idx)
                severity failure;
            
            wait for CLK_PERIOD;
            load_en <= '0';
            wait for CLK_PERIOD;
            
            --LOAD C
            
            clear_rf_ports(rf_rd_data_port_a, rf_rd_data_port_b);
            
            load_en <= '1';
            load_ph <= "10"; -- C buffers;
            load_pair <= "00";
            
            load_8_lanes_from_file(tb_file, rf_rd_data_port_a, rf_rd_data_port_b, have_data);
            
            assert have_data
                report "Stimulus file ended unexpectedly while reading C block for test " &
                    integer'image(test_idx)
                severity failure;
                
            wait for CLK_PERIOD;    
            load_en <= '0';
            wait for CLK_PERIOD;
            
            --Execution sweep for HMMAstep0
            --each cycle produces one 1x4 row for D00 and one 1x4 row for D20
            
            exec_step <= "00";
            wait for CLK_PERIOD;
            for c in 0 to 3 loop
                D00_capture(0, c) := W0_16_X3(c);
                D20_capture(0, c) := W1_16_X3(c);
            end loop;
            
            exec_step <= "01";
            wait for CLK_PERIOD;
            for c in 0 to 3 loop 
                D00_capture(1, c) := W0_16_X3(c);
                D20_capture(1, c) := W1_16_X3(c);
            end loop;
            
            exec_step <= "10";
            wait for CLK_PERIOD;
            for c in 0 to 3 loop
                D00_capture(2, c) := W0_16_X3(c);
                D20_capture(2, c) := W1_16_X3(c);
            end loop;
            
            exec_step <= "11";
            wait for CLK_PERIOD;
            for c in 0 to 3 loop
                D00_capture(3, c) := W0_16_X3(c);
                D20_capture(3, c) := W1_16_X3(c);
            end loop;
            
            -- write results for this test
            write_test_result(tb_out_file, test_idx, D00_capture, D20_capture);
            
            --optional idle cycle between tests
            clear_rf_ports(rf_rd_data_port_a, rf_rd_data_port_b);
            exec_step <= "00";
            wait for CLK_PERIOD;
            
            report "Completed HMMAstep0 test #" & integer'image(test_idx);
        
            --focusing on only the first hmma step0 instruction
            --if test_idx = 1 then
            --    report "Stopping after HMMAstep0 test." severity note;
            --    wait;
            --end if;
        end loop;
        
        wait for 5* CLK_PERIOD;
        assert false report "End of file reached. End of testbench." severity failure;
    
    end process;        
            
end sim;
